package cn.edu.xmu.oomall.alipay.model.po;

import java.time.LocalDateTime;

public class AlipayPaymentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.send_pay_date
     *
     * @mbg.generated
     */
    private LocalDateTime sendPayDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.total_amount
     *
     * @mbg.generated
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.buyer_pay_amount
     *
     * @mbg.generated
     */
    private Long buyerPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_payment.trade_status
     *
     * @mbg.generated
     */
    private Byte tradeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.id
     *
     * @return the value of oomall_alipay_payment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.id
     *
     * @param id the value for oomall_alipay_payment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.out_trade_no
     *
     * @return the value of oomall_alipay_payment.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.out_trade_no
     *
     * @param outTradeNo the value for oomall_alipay_payment.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.send_pay_date
     *
     * @return the value of oomall_alipay_payment.send_pay_date
     *
     * @mbg.generated
     */
    public LocalDateTime getSendPayDate() {
        return sendPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.send_pay_date
     *
     * @param sendPayDate the value for oomall_alipay_payment.send_pay_date
     *
     * @mbg.generated
     */
    public void setSendPayDate(LocalDateTime sendPayDate) {
        this.sendPayDate = sendPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.total_amount
     *
     * @return the value of oomall_alipay_payment.total_amount
     *
     * @mbg.generated
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.total_amount
     *
     * @param totalAmount the value for oomall_alipay_payment.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.buyer_pay_amount
     *
     * @return the value of oomall_alipay_payment.buyer_pay_amount
     *
     * @mbg.generated
     */
    public Long getBuyerPayAmount() {
        return buyerPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.buyer_pay_amount
     *
     * @param buyerPayAmount the value for oomall_alipay_payment.buyer_pay_amount
     *
     * @mbg.generated
     */
    public void setBuyerPayAmount(Long buyerPayAmount) {
        this.buyerPayAmount = buyerPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_payment.trade_status
     *
     * @return the value of oomall_alipay_payment.trade_status
     *
     * @mbg.generated
     */
    public Byte getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_payment.trade_status
     *
     * @param tradeStatus the value for oomall_alipay_payment.trade_status
     *
     * @mbg.generated
     */
    public void setTradeStatus(Byte tradeStatus) {
        this.tradeStatus = tradeStatus;
    }
}