package cn.edu.xmu.oomall.alipay.model.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class AlipayRefundPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.out_request_no
     *
     * @mbg.generated
     */
    private String outRequestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.refund_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.gmt_refund_pay
     *
     * @mbg.generated
     */
    private LocalDateTime gmtRefundPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_alipay_refund.refund_status
     *
     * @mbg.generated
     */
    private Byte refundStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.id
     *
     * @return the value of oomall_alipay_refund.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.id
     *
     * @param id the value for oomall_alipay_refund.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.out_trade_no
     *
     * @return the value of oomall_alipay_refund.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.out_trade_no
     *
     * @param outTradeNo the value for oomall_alipay_refund.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.out_request_no
     *
     * @return the value of oomall_alipay_refund.out_request_no
     *
     * @mbg.generated
     */
    public String getOutRequestNo() {
        return outRequestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.out_request_no
     *
     * @param outRequestNo the value for oomall_alipay_refund.out_request_no
     *
     * @mbg.generated
     */
    public void setOutRequestNo(String outRequestNo) {
        this.outRequestNo = outRequestNo == null ? null : outRequestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.total_amount
     *
     * @return the value of oomall_alipay_refund.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.total_amount
     *
     * @param totalAmount the value for oomall_alipay_refund.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.refund_amount
     *
     * @return the value of oomall_alipay_refund.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.refund_amount
     *
     * @param refundAmount the value for oomall_alipay_refund.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.gmt_refund_pay
     *
     * @return the value of oomall_alipay_refund.gmt_refund_pay
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtRefundPay() {
        return gmtRefundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.gmt_refund_pay
     *
     * @param gmtRefundPay the value for oomall_alipay_refund.gmt_refund_pay
     *
     * @mbg.generated
     */
    public void setGmtRefundPay(LocalDateTime gmtRefundPay) {
        this.gmtRefundPay = gmtRefundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_alipay_refund.refund_status
     *
     * @return the value of oomall_alipay_refund.refund_status
     *
     * @mbg.generated
     */
    public Byte getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_alipay_refund.refund_status
     *
     * @param refundStatus the value for oomall_alipay_refund.refund_status
     *
     * @mbg.generated
     */
    public void setRefundStatus(Byte refundStatus) {
        this.refundStatus = refundStatus;
    }
}