package cn.edu.xmu.oomall.alipay.mapper;

import cn.edu.xmu.oomall.alipay.model.po.AlipayRefundPo;
import cn.edu.xmu.oomall.alipay.model.po.AlipayRefundPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipayRefundPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int insert(AlipayRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int insertSelective(AlipayRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    List<AlipayRefundPo> selectByExample(AlipayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    AlipayRefundPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlipayRefundPo record, @Param("example") AlipayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlipayRefundPo record, @Param("example") AlipayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlipayRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlipayRefundPo record);
}