package cn.edu.xmu.oomall.alipay.mapper;

import cn.edu.xmu.oomall.alipay.model.po.AlipayPaymentPo;
import cn.edu.xmu.oomall.alipay.model.po.AlipayPaymentPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipayPaymentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int insert(AlipayPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int insertSelective(AlipayPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    List<AlipayPaymentPo> selectByExample(AlipayPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    AlipayPaymentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlipayPaymentPo record, @Param("example") AlipayPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlipayPaymentPo record, @Param("example") AlipayPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlipayPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_alipay_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlipayPaymentPo record);
    
    AlipayPaymentPo queryPaymentByTradeNo(String tradNo);
}