package cn.edu.xmu.oomall.wechatpay.mapper;

import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayDivRefundTransPo;
import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayDivRefundTransPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WeChatPayDivRefundTransPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wechatpay_div_refund",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wechatpay_div_refund (`out_return_no`, `out_order_no`, ",
        "`amount`, `success_time`)",
        "values (#{outReturnNo,jdbcType=VARCHAR}, #{outOrderNo,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=INTEGER}, #{successTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(WeChatPayDivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @InsertProvider(type=WeChatPayDivRefundTransPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(WeChatPayDivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @SelectProvider(type=WeChatPayDivRefundTransPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_return_no", property="outReturnNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_order_no", property="outOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WeChatPayDivRefundTransPo> selectByExample(WeChatPayDivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `out_return_no`, `out_order_no`, `amount`, `success_time`",
        "from wechatpay_div_refund",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_return_no", property="outReturnNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_order_no", property="outOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WeChatPayDivRefundTransPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivRefundTransPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") WeChatPayDivRefundTransPo row, @Param("example") WeChatPayDivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivRefundTransPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") WeChatPayDivRefundTransPo row, @Param("example") WeChatPayDivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivRefundTransPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeChatPayDivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_refund
     *
     * @mbg.generated
     */
    @Update({
        "update wechatpay_div_refund",
        "set `out_return_no` = #{outReturnNo,jdbcType=VARCHAR},",
          "`out_order_no` = #{outOrderNo,jdbcType=VARCHAR},",
          "`amount` = #{amount,jdbcType=INTEGER},",
          "`success_time` = #{successTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WeChatPayDivRefundTransPo row);
}