package cn.edu.xmu.oomall.wechatpay.mapper;

import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayRefundPo;
import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayRefundPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WeChatPayRefundPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wechatpay_refund",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wechatpay_refund (`out_refund_no`, `out_trade_no`, ",
        "`status`, `refund`, ",
        "`payer_total`, `success_time`)",
        "values (#{outRefundNo,jdbcType=VARCHAR}, #{outTradeNo,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{refund,jdbcType=INTEGER}, ",
        "#{payerTotal,jdbcType=INTEGER}, #{successTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(WeChatPayRefundPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @InsertProvider(type=WeChatPayRefundPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(WeChatPayRefundPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @SelectProvider(type=WeChatPayRefundPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_refund_no", property="outRefundNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund", property="refund", jdbcType=JdbcType.INTEGER),
        @Result(column="payer_total", property="payerTotal", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WeChatPayRefundPo> selectByExample(WeChatPayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `out_refund_no`, `out_trade_no`, `status`, `refund`, `payer_total`, `success_time`",
        "from wechatpay_refund",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_refund_no", property="outRefundNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund", property="refund", jdbcType=JdbcType.INTEGER),
        @Result(column="payer_total", property="payerTotal", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WeChatPayRefundPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayRefundPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") WeChatPayRefundPo row, @Param("example") WeChatPayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayRefundPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") WeChatPayRefundPo row, @Param("example") WeChatPayRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayRefundPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeChatPayRefundPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund
     *
     * @mbg.generated
     */
    @Update({
        "update wechatpay_refund",
        "set `out_refund_no` = #{outRefundNo,jdbcType=VARCHAR},",
          "`out_trade_no` = #{outTradeNo,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=VARCHAR},",
          "`refund` = #{refund,jdbcType=INTEGER},",
          "`payer_total` = #{payerTotal,jdbcType=INTEGER},",
          "`success_time` = #{successTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WeChatPayRefundPo row);
}