package cn.edu.xmu.oomall.wechatpay.mapper;

import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayDivPayTransPo;
import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayDivPayTransPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WeChatPayDivPayTransPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wechatpay_div_pay",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wechatpay_div_pay (`out_trade_no`, `out_order_no`, ",
        "`state`, `payer_total`, ",
        "`success_time`)",
        "values (#{outTradeNo,jdbcType=VARCHAR}, #{outOrderNo,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=VARCHAR}, #{payerTotal,jdbcType=INTEGER}, ",
        "#{successTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(WeChatPayDivPayTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @InsertProvider(type=WeChatPayDivPayTransPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(WeChatPayDivPayTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @SelectProvider(type=WeChatPayDivPayTransPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_order_no", property="outOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="payer_total", property="payerTotal", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WeChatPayDivPayTransPo> selectByExample(WeChatPayDivPayTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `out_trade_no`, `out_order_no`, `state`, `payer_total`, `success_time`",
        "from wechatpay_div_pay",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_order_no", property="outOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="payer_total", property="payerTotal", jdbcType=JdbcType.INTEGER),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WeChatPayDivPayTransPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivPayTransPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") WeChatPayDivPayTransPo row, @Param("example") WeChatPayDivPayTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivPayTransPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") WeChatPayDivPayTransPo row, @Param("example") WeChatPayDivPayTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WeChatPayDivPayTransPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeChatPayDivPayTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_div_pay
     *
     * @mbg.generated
     */
    @Update({
        "update wechatpay_div_pay",
        "set `out_trade_no` = #{outTradeNo,jdbcType=VARCHAR},",
          "`out_order_no` = #{outOrderNo,jdbcType=VARCHAR},",
          "`state` = #{state,jdbcType=VARCHAR},",
          "`payer_total` = #{payerTotal,jdbcType=INTEGER},",
          "`success_time` = #{successTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WeChatPayDivPayTransPo row);
}